-- Disposable database only. Run separately from the profile fixture database.
\set ON_ERROR_STOP on
do $$begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon;end if;if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated;end if;end$$;
create schema auth;
create table auth.users(id uuid primary key,email text);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public to anon,authenticated;
\ir ../migrations/20260925000001_content_manager.sql
\ir ../migrations/20260925000001_content_manager.sql
create function public.test_assert(ok boolean,message text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',message;end if;end$$;
create function public.test_reject(query text) returns void language plpgsql as $$begin begin execute query;exception when others then return;end;raise exception 'FAIL: query unexpectedly accepted: %',query;end$$;
begin;
insert into auth.users values ('11111111-1111-4111-8111-111111111111','admin'),('22222222-2222-4222-8222-222222222222','teacher');
insert into question_admins(user_id) values ('11111111-1111-4111-8111-111111111111');
set local role authenticated;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
insert into questions(id,type,subject_id,chapter,payload) values ('q1','mcq','physics','Chapter 1','{"questionText":"Test question","options":["A","B","C","D"],"correctIndex":1,"explanation":"Source explanation"}');
select test_assert((select review_status='draft' from questions where id='q1'),'new content starts as draft');
select test_reject($q$update questions set review_status='published' where id='q1'$q$);
select test_reject($q$delete from questions where id='q1'$q$);
update questions set review_status='review' where id='q1';
update questions set review_status='published' where id='q1';
select test_reject($q$update questions set payload=payload||'{"correctIndex":0}' where id='q1'$q$);
select test_reject($q$update questions set id='renamed' where id='q1'$q$);
insert into questions(id,type,subject_id,chapter,payload) select 'duplicate',type,subject_id,chapter,payload from questions where id='q1';
update questions set review_status='review' where id='duplicate';
select test_reject($q$update questions set review_status='published' where id='duplicate'$q$);
insert into english_papers(id,paper_type,board,year,subject,data) values ('english1','first','Dhaka',2024,'english_1st', $first${"schema_version": 1, "answers": {"q1": null, "q2": null, "q3": null, "q4": null, "q5": null, "q6": null, "q7": null, "q8": null, "q9": null, "q10": null, "q11": null}, "passage1Intro": "Test source: passage1Intro", "passage1Unit": "Test source: passage1Unit", "passage1": "Test source: passage1", "q1Instr": "Test source: q1Instr", "q1": [{"stem": "Source question 0", "options": ["one", "two", "three", "four"]}, {"stem": "Source question 1", "options": ["one", "two", "three", "four"]}, {"stem": "Source question 2", "options": ["one", "two", "three", "four"]}, {"stem": "Source question 3", "options": ["one", "two", "three", "four"]}, {"stem": "Source question 4", "options": ["one", "two", "three", "four"]}, {"stem": "Source question 5", "options": ["one", "two", "three", "four"]}, {"stem": "Source question 6", "options": ["one", "two", "three", "four"]}], "q2": ["Source line 0", "Source line 1", "Source line 2", "Source line 3", "Source line 4"], "q3Instr": "Test source: q3Instr", "q3Source": "Test source: q3Source", "q3Unit": "Test source: q3Unit", "q3Cloze": "Test source: q3Cloze", "passage2Intro": "Test source: passage2Intro", "passage2": "Test source: passage2", "q4Instr": "Test source: q4Instr", "q4Table": [["Name", "Year"], ["Source", "(i)"]], "q4BoldRows": [0], "q6A": ["Source line 0", "Source line 1", "Source line 2"], "q6B": ["Source line 0", "Source line 1", "Source line 2"], "q6C": ["Source line 0", "Source line 1", "Source line 2"], "q7": ["Source line 0", "Source line 1", "Source line 2", "Source line 3", "Source line 4", "Source line 5", "Source line 6", "Source line 7"], "q8": ["Source line 0", "Source line 1", "Source line 2"], "q9": ["Source line 0", "Source line 1", "Source line 2"], "q10Instr": "Test source: q10Instr", "q10Starter": "Test source: q10Starter", "q11": "Test source: q11"}$first$),('english2','second','Dhaka',2024,'english_2nd',$second${"schema_version": 1, "answers": {"q1": null, "q2": null, "q3": null, "q4": null, "q5": null, "q6": null, "q7": null, "q8": null, "q9": null, "q10": null, "q11": null, "q12": null}, "headerExtra": ["Source line 0", "Source line 1", "Source line 2"], "q1Box": ["Source line 0", "Source line 1", "Source line 2"], "q1Passage": "Test source: q1Passage", "q2": [{"a": "Source", "b": "", "c": "text"}], "q3Box": ["Source line 0", "Source line 1", "Source line 2"], "q3Passage": "Test source: q3Passage", "q4": [{"sentence": "Source sentence 0", "direction": "Assertive"}, {"sentence": "Source sentence 1", "direction": "Assertive"}, {"sentence": "Source sentence 2", "direction": "Assertive"}, {"sentence": "Source sentence 3", "direction": "Assertive"}, {"sentence": "Source sentence 4", "direction": "Assertive"}, {"sentence": "Source sentence 5", "direction": "Assertive"}, {"sentence": "Source sentence 6", "direction": "Assertive"}, {"sentence": "Source sentence 7", "direction": "Assertive"}, {"sentence": "Source sentence 8", "direction": "Assertive"}, {"sentence": "Source sentence 9", "direction": "Assertive"}], "q5": ["Source line 0", "Source line 1", "Source line 2", "Source line 3", "Source line 4"], "q6Passage": "Test source: q6Passage", "q7Passage": "Test source: q7Passage", "q8Passage": "Test source: q8Passage", "q9Text": "Test source: q9Text", "q10": "Test source: q10", "q11": "Test source: q11", "q12": "Test source: q12"}$second$);
update english_papers set review_status='review';
update english_papers set review_status='published';
select test_reject($q$update english_papers set data=jsonb_set(data,'{q1,0,options,0}','null'),review_status='review' where id='english1'$q$);
select test_reject($q$update english_papers set data=jsonb_set(data,'{q4,0,direction}','null'),review_status='review' where id='english2'$q$);
select test_reject($q$insert into admin_activity(action,entity,record_id,metadata) values ('fake','questions','q1','{}')$q$);
set local role anon;
select set_config('request.jwt.claim.sub','',true);
select test_assert((select count(*)=1 from questions),'only published question is public');
select test_assert((select count(*)=2 from english_papers),'published English readable');
select test_reject($q$insert into questions(id,type,subject_id,chapter,payload)values('anon','saq','physics','C','{}')$q$);
set local role authenticated;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
select test_assert(not is_question_admin(),'teacher is not admin');
select test_assert((select count(*)=0 from admin_activity),'audit hidden from teachers');
select test_reject($q$insert into english_papers(id,paper_type,board,year,subject,data) values('bad','first','Dhaka',2024,'english_1st','{}')$q$);
select test_reject($q$insert into question_admins(user_id)values(auth.uid())$q$);
select test_reject($q$insert into questions(id,type,subject_id,chapter,payload)values('official','saq','physics','C','{}')$q$);
insert into questions(id,type,subject_id,chapter,payload,owner_id)values('private','saq','physics','C','{}',auth.uid());
select test_assert((select count(*)=2 from questions),'teacher can see own draft plus official');
set local role authenticated;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
update questions set is_active=false where id='q1';
update english_papers set is_active=false where id='english1';
select test_assert((select count(*)>0 from admin_activity where action='archive'),'archive audited');
select test_assert((select count(*)=0 from admin_activity where record_id='private'),'private content not copied into audit');
set local role anon;
select set_config('request.jwt.claim.sub','',true);
select test_assert((select count(*)=1 from question_tombstones where id='q1'),'retirement IDs are public');
select test_assert((select count(*)=0 from question_tombstones where id='private'),'private IDs are not retired publicly');
select test_assert((select count(*)=0 from questions),'archive is not public');
select test_assert((select count(*)=1 from english_papers),'archived English hidden');
set local role authenticated;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
update questions set is_active=true where id='q1';
select test_assert((select count(*)=0 from question_tombstones where id='q1'),'restore removes retirement marker');
select test_assert((select count(*)=1 from admin_activity where action='restore'),'restore audited');
update questions set review_status='draft',payload=jsonb_set(payload,'{correctIndex}','null') where id='q1';
select test_reject($q$update questions set review_status='review' where id='q1'$q$);
rollback;
