import 'question_bank.dart';

/// Provenance of a question.
///
/// `ai` and `board` keep their original positions so any persisted index
/// stays valid; `original` and `internet` are appended for the physics bank.
enum QuestionSource { ai, board, original, internet }

class Question {
  final String id;
  final String subjectId;
  final String chapter;
  final String questionText;
  final List<String> options;
  final int correctIndex;
  final String explanation;
  final QuestionSource source;
  final String? sourceLabel;
  final QuestionFigure? figure;

  const Question({
    required this.id,
    required this.subjectId,
    required this.chapter,
    required this.questionText,
    required this.options,
    required this.correctIndex,
    required this.explanation,
    this.source = QuestionSource.ai,
    this.sourceLabel,
    this.figure,
  });
}

/// A short-answer (SAQ) question.
///
/// Additive: `Question` and `CreativeQuestion` are untouched.
class ShortQuestion {
  final String id;
  final String subjectId;
  final String chapter;
  final String questionText;
  final String answer;
  final String explanation;
  final QuestionSource source;
  final String? sourceLabel;
  final QuestionFigure? figure;

  const ShortQuestion({
    required this.id,
    required this.subjectId,
    required this.chapter,
    required this.questionText,
    required this.answer,
    this.explanation = '',
    this.source = QuestionSource.ai,
    this.sourceLabel,
    this.figure,
  });
}

class CreativeQuestion {
  final String id;
  final String subjectId;
  final String chapter;
  final String stem;
  final String questionK;
  final String questionKh;
  final String questionG;
  final String questionGh;
  final List<int> marks;
  final QuestionSource source;
  final String? sourceLabel;
  final QuestionFigure? figure;

  const CreativeQuestion({
    required this.id,
    required this.subjectId,
    required this.chapter,
    required this.stem,
    required this.questionK,
    required this.questionKh,
    required this.questionG,
    required this.questionGh,
    this.marks = const [1, 2, 3, 4],
    this.source = QuestionSource.ai,
    this.sourceLabel,
    this.figure,
  });
}

// ── The bank itself ──────────────────────────────────────────────────
//
// These used to be ~7,000 lines of `const` literals in this file plus ~250k
// more across lib/data/**. They now live in assets/questions/*.json,
// generated by tool/extract_questions.py and read by QuestionBank.
//
// The names and types are unchanged, so every existing call site still
// works. `QuestionBank.load()` must have completed first; main() awaits it
// before runApp.

/// All multiple-choice questions.
List<Question> get allMCQs => QuestionBank.mcqs;

/// All creative (CQ) questions.
List<CreativeQuestion> get allCQs => QuestionBank.cqs;

/// All short-answer (SAQ) questions.
List<ShortQuestion> get allSAQs => QuestionBank.saqs;
